# Generated by Django 5.2 on 2025-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Неуспешно')], max_length=20, verbose_name='Статус')),
                ('response', models.TextField(verbose_name='Ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Первая отправка')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание отправки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('launched', 'Запущена')], max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['message', 'owner'],
                'permissions': [('can_stop_mailing', 'Can stop mailing')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'permissions': [('can_view_message', 'Can view message')],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
                'permissions': [('can_view_recipient', 'Can view recipient')],
            },
        ),
    ]
